import { execFileSync } from "node:child_process";
import { randomBytes } from "node:crypto";
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";

import { createClient } from "@supabase/supabase-js";

const cli = resolve(
  "node_modules",
  ".bin",
  process.platform === "win32" ? "supabase.cmd" : "supabase",
);

function statusJson() {
  const output = execFileSync(cli, ["status", "--output", "json"], {
    encoding: "utf8",
    stdio: ["ignore", "pipe", "pipe"],
  });
  return JSON.parse(output);
}

function pick(status, ...keys) {
  for (const key of keys) {
    if (typeof status[key] === "string" && status[key]) return status[key];
  }
  throw new Error(`Local Supabase did not report ${keys[0]}.`);
}

function requireLoopback(value, label) {
  const url = new URL(value);
  if (url.protocol !== "http:" || !["127.0.0.1", "localhost", "::1"].includes(url.hostname)) {
    throw new Error(`${label} is not an explicit loopback URL. Local setup stopped safely.`);
  }
  return url.toString().replace(/\/$/u, "");
}

const status = statusJson();
const apiUrl = requireLoopback(pick(status, "API_URL", "api_url"), "Supabase API");
const studioUrl = requireLoopback(pick(status, "STUDIO_URL", "studio_url"), "Supabase Studio");
const inbucketUrl = requireLoopback(
  pick(status, "INBUCKET_URL", "inbucket_url"),
  "Supabase Inbucket",
);
const publishableKey = pick(status, "ANON_KEY", "anon_key", "PUBLISHABLE_KEY", "publishable_key");
const serviceRoleKey = pick(status, "SERVICE_ROLE_KEY", "service_role_key");

const env = [
  "# Generated by pnpm setup:local. This file is ignored by Git.",
  "NEXT_PUBLIC_SITE_URL=http://127.0.0.1:3000",
  "NEXT_PUBLIC_INDEXING_ENABLED=false",
  "NEXT_PUBLIC_IDENTITY_APPROVED=true",
  "NEXT_PUBLIC_DEMO_MODE=true",
  `NEXT_PUBLIC_SUPABASE_URL=${apiUrl}`,
  `NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY=${publishableKey}`,
  `SUPABASE_SERVICE_ROLE_KEY=${serviceRoleKey}`,
  "ENQUIRY_TRUSTED_IP_HEADER=x-forwarded-for",
  `ENQUIRY_FINGERPRINT_PEPPER=${randomBytes(32).toString("hex")}`,
  `CRON_SECRET=${randomBytes(32).toString("hex")}`,
  "NEXT_PUBLIC_ERROR_MONITORING_DSN=",
  "",
].join("\n");
writeFileSync(resolve(".env.local"), env, { encoding: "utf8", mode: 0o600 });

const client = createClient(apiUrl, serviceRoleKey, {
  auth: { autoRefreshToken: false, detectSessionInUrl: false, persistSession: false },
});

const accounts = [
  {
    email: process.env.LOCAL_ADMIN_EMAIL?.trim().toLowerCase() || "admin.local@example.test",
    display_name: "Local super administrator",
    role: "super_admin",
  },
  {
    email: "editor.local@example.test",
    display_name: "Local website editor",
    role: "website_editor",
  },
  {
    email: "prayer.local@example.test",
    display_name: "Local prayer editor",
    role: "prayer_editor",
  },
  {
    email: "enquiries.local@example.test",
    display_name: "Local enquiries manager",
    role: "enquiries_manager",
  },
  {
    email: "reviewer.local@example.test",
    display_name: "Local read-only reviewer",
    role: "reviewer",
  },
];

let superAdminId = "";
for (const account of accounts) {
  const created = await client.auth.admin.createUser({
    email: account.email,
    email_confirm: true,
    user_metadata: { display_name: account.display_name, local_demo: true },
  });
  if (created.error || !created.data.user)
    throw created.error ?? new Error("Local user creation failed.");
  const userId = created.data.user.id;
  if (account.role === "super_admin") superAdminId = userId;
  const profile = await client.from("admin_profiles").insert({
    id: userId,
    display_name: account.display_name,
    role: account.role,
    status: "active",
    mfa_required: true,
  });
  if (profile.error) throw profile.error;
}

const seeded = await client.rpc("seed_local_demo_data", {
  p_actor_id: superAdminId,
  p_marker: "LOCAL_DEMO_ONLY",
});
if (seeded.error) throw seeded.error;

const adminEmail = accounts[0].email;
const link = await client.auth.admin.generateLink({
  type: "magiclink",
  email: adminEmail,
});
const hashedToken = link.data.properties?.hashed_token;
if (link.error || !hashedToken) {
  throw link.error ?? new Error("A local administrator sign-in link could not be generated.");
}
const localSignInUrl = new URL("http://127.0.0.1:3000/admin/auth/callback");
localSignInUrl.searchParams.set("token_hash", hashedToken);
localSignInUrl.searchParams.set("type", "magiclink");

console.log("\nLocal product environment is ready.\n");
console.log("Start the application:  pnpm dev");
console.log("Public website:         http://127.0.0.1:3000");
console.log("Administration:         http://127.0.0.1:3000/admin/sign-in");
console.log(`Supabase Studio:        ${studioUrl}`);
console.log(`Captured email:         ${inbucketUrl}`);
console.log(`Local administrator:    ${adminEmail}`);
if (process.env.CI) {
  console.log(
    "One-time sign-in link:   omitted from CI logs (the acceptance test creates its own)",
  );
} else {
  console.log("One-time sign-in link:");
  console.log(localSignInUrl.toString());
}
console.log(
  "\nAfter signing in, enrol and confirm TOTP on /admin/security before changing protected data.",
);
console.log("Generate another one-time role-account link with: pnpm local:link -- <email>");
console.log(
  "All sample values are visibly marked LOCAL DEMO and exist only in this loopback stack.\n",
);
